### PR TITLE
Fixing compile

### PR DESCRIPTION
**Pull request by rbedfordpro**

### CODE REVIEW

**Comment by rbedfordpro** [comment]
Allows compile with `-DNOPCH=1`

**Comment by BarbzYHOOL** [comment]
gonna test this out

**Comment by BarbzYHOOL** [comment]
sorry, i just compiled to test (still busy with stuff) and it worked fine, can't test ingame for now tho

**Comment by BarbzYHOOL** [comment]
merged, thank you @rbedfordpro

**Pull request merged**
